Feature/login
YuvalShvartsman/FitBFF-client pull request #3
Opened 2024-07-19 13:45 UTC by benada1

this feature allows signing into a gmail user and creates that user, or updates him in the users database

2024-07-20 06:06 UTC, YuvalShvartsman requested changes
Please fix this before we strart new week.

2024-07-21 17:01 UTC, benada1 commented on src/components/Login/GoogleLogin/GoogleLogin.tsx
> +const clientId =
using env in client side is a thing that allows exposure to risks and in general isnt a positive thing to have at all at clilent side, doesnt matter if its in an env file or in the main file the api is at risk of being found and exposed, from what ive seen over the internet all actions with the api should be done on the server side and there should be no necessity for the client id in the first place, which means there needs to be serious changes happening if you want to actually fix this problem because most of the code is invlaid without the usage of the api in client side

2024-07-21 17:02 UTC, benada1 commented on src/components/Login/GoogleLogin/GoogleLogin.tsx
> +import React from "react";
removed and fixed

2024-07-21 17:26 UTC, benada1 commented on src/components/Login/GoogleLogin/GoogleLogin.tsx
> +      console.log("Server response:", response.data);
implemented swal in UseGoogleLogin.tsx when it sends back whether the login was successful or an error

2024-07-21 17:27 UTC, benada1 commented on src/components/Login/GoogleLogin/GoogleLogin.tsx
> +      console.error("Error sending token to server:", error);
done.

2024-07-21 18:18 UTC, benada1 commented on src/components/Login/GoogleLogin/GoogleLogin.tsx
> +const GoogleLogin: React.FC = () => {
just chganged it to a regular function instead of making a const and starting the function from him.

2024-07-21 18:30 UTC, merged